version: '3.8'

services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5432:5432
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - area-network

    redis:
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
        networks:
            - area-network

    server:
        build: ./packages/server
        restart: always
        ports:
            - 8080:8080
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_SSLMODE: ${POSTGRES_SSLMODE}

            REDIS_HOST: redis
            REDIS_PORT: 6379

            AREA_STATE: ${AREA_STATE}
            JWT_SECRET: ${JWT_SECRET}
        env_file:
            - ./.services
        depends_on:
            - postgres
        networks:
            - area-network

    client_mobile:
        build: ./packages/mobile
        restart: "no"
        depends_on:
            - server
        volumes:
            - client_data:/data

    client_web:
        build: ./packages/web
        restart: always
        ports:
            - 8081:8081
        #depends_on:
        #    - client_mobile
        volumes:
            - client_data:/data
        networks:
            - area-network

    nginx:
        image: nginx:1.23.3
        restart: always
        depends_on:
            - postgres
            - server
            - client_web
        volumes:
            - ./packages/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        networks:
            - area-network

volumes:
    db_data: {}
    client_data: {}
    redis_data: {}

networks:
    area-network:
        driver: bridge
